### PR TITLE
Fix keyrepeat not working in the tty

### LINKED ISSUE #188: Key repeat in the tty?
Hello,
I wanted to use kmonad to remap the backspace and caps lock keys, I used it since it can work with low-level keyboard input which is suitable for use with tty (unlike something like xmodmap). However, there is no key repeat or at least an option that makes it possible I know of, I think key repeat works in X server due to other X specific programs, I think this may be related to #82 or #184 but for linux.
Thanks for reading my issue.

### LINKED ISSUE #543: Hold key doesn't work as expected in tty
Hello. When i hold `h` key in my vim or file manager I expect scrolling to bottom.
With enabled kmonad it works as expected in `sway` wm but it doesnt in tty. It does only one jump and stop.

How to fix it?

### PR DESCRIPTION
**Pull request by jokesper**
Apparently we just needed to set an extra flag.
See [Blagus's comment](https://forums.raspberrypi.com/viewtopic.php?t=45041#p1066932) linking to [Using uinput driver in Linux-2.6.x](https://www.geocities.ws/gnumohan/Linux/uinput.txt).

Fixes #188. Though we should really be looking into implementing it in KMonad like #867 suggest.
Also fixes #543.

### CODE REVIEW

File: c_src/keyio.c [hunk 1]
```diff
@@ -21,6 +21,8 @@ int acquire_uinput_keysink(int fd, char *name, int vendor, int product, int vers
   for (i=0; i < 256; i++) {
     ioctl(fd, UI_SET_KEYBIT, i);
   }
+  // Enable key repeat for output keyboard
+  ioctl(fd, UI_SET_EVBIT, EV_REP);
```
Comment (jian-lin) [inline c_src/keyio.c:25]: I am not sure why we do not check `ioctl` return values in this `acquire_uinput_keysink` function.  Probably we should do that like what we do in other functions.

It may be out of the scope of this PR thought and we can do that in a future PR.

Comment (jokesper) [reply c_src/keyio.c:25]: Probably, though I think checking the length by the `strcpy` is also something important, since you can trivially type more than 80 characters in the `uinput-sink <name>` parameter.

Comment (jokesper) [reply c_src/keyio.c:25]: I fixed the overflow and some types in [my local branch](https://github.com/jokesper/kmonad/tree/fix-c). Though this doesn't add checks in the C code. If you want you could do it. (Either independently or as a PR against my branch)

**Comment by slotThe** [comment]
Thanks! I agree that the C code could probably use some more love, in case anyone wants to do that
